# Site settings
title: Kushal Mangtani Blogs!
email: mangtani.kushal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 This is where I post everything! I am going to be bold and honest in this blog. Beware pussies!
baseurl: /jekyll-stuff
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username : kushalmangtani


# Build settings
markdown: kramdown
